version: "3.8"
services:
  api:
    build: .
    container_name: rag_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - LLM_PROVIDER=ollama
      - OLLAMA_HOST=host.docker.internal
      - OLLAMA_PORT=11434
